languagesList = [
    ('aa', 'Afar'),
    ('ab', 'Abkhazian'),
    ('af', 'Afrikaans'),
    ('ak', 'Akan'),
    ('sq', 'Albanian'),
    ('am', 'Amharic'),
    ('ar', 'Arabic'),
    ('an', 'Aragonese'),
    ('hy', 'Armenian'),
    ('as', 'Assamese'),
    ('av', 'Avaric'),
    ('ae', 'Avestan'),
    ('ay', 'Aymara'),
    ('az', 'Azerbaijani'),
    ('ba', 'Bashkir'),
    ('bm', 'Bambara'),
    ('eu', 'Basque'),
    ('be', 'Belarusian'),
    ('bn', 'Bengali'),
    ('bh', 'Bihari languages'),
    ('bi', 'Bislama'),
    ('bo', 'Tibetan'),
    ('bs', 'Bosnian'),
    ('br', 'Breton'),
    ('bg', 'Bulgarian'),
    ('my', 'Burmese'),
    ('ca', 'Catalan; Valencian'),
    ('cs', 'Czech'),
    ('ch', 'Chamorro'),
    ('ce', 'Chechen'),
    ('zh', 'Chinese'),
    ('cu', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'),
    ('cv', 'Chuvash'),
    ('kw', 'Cornish'),
    ('co', 'Corsican'),
    ('cr', 'Cree'),
    ('cy', 'Welsh'),
    ('cs', 'Czech'),
    ('da', 'Danish'),
    ('de', 'German'),
    ('dv', 'Divehi; Dhivehi; Maldivian'),
    ('nl', 'Dutch; Flemish'),
    ('dz', 'Dzongkha'),
    ('el', 'Greek, Modern (1453-)'),
    ('en', 'English'),
    ('eo', 'Esperanto'),
    ('et', 'Estonian'),
    ('eu', 'Basque'),
    ('ee', 'Ewe'),
    ('fo', 'Faroese'),
    ('fa', 'Persian'),
    ('fj', 'Fijian'),
    ('fi', 'Finnish'),
    ('fr', 'French'),
    ('fy', 'Western Frisian'),
    ('ff', 'Fulah'),
    ('Ga', 'Georgian'),
    ('de', 'German'),
    ('gd', 'Gaelic; Scottish Gaelic'),
    ('ga', 'Irish'),
    ('gl', 'Galician'),
    ('gv', 'Manx'),
    ('el', 'Greek, Modern (1453-)'),
    ('gn', 'Guarani'),
    ('gu', 'Gujarati'),
    ('ht', 'Haitian; Haitian Creole'),
    ('ha', 'Hausa'),
    ('he', 'Hebrew'),
    ('hz', 'Herero'),
    ('hi', 'Hindi'),
    ('ho', 'Hiri Motu'),
    ('hr', 'Croatian'),
    ('hu', 'Hungarian'),
    ('hy', 'Armenian'),
    ('ig', 'Igbo'),
    ('is', 'Icelandic'),
    ('io', 'Ido'),
    ('ii', 'Sichuan Yi; Nuosu'),
    ('iu', 'Inuktitut'),
    ('ie', 'Interlingue; Occidental'),
    ('ia', 'Interlingua (International Auxiliary Language Association)'),
    ('id', 'Indonesian'),
    ('ik', 'Inupiaq'),
    ('is', 'Icelandic'),
    ('it', 'Italian'),
    ('jv', 'Javanese'),
    ('ja', 'Japanese'),
    ('kl', 'Kalaallisut; Greenlandic'),
    ('kn', 'Kannada'),
    ('ks', 'Kashmiri'),
    ('ka', 'Georgian'),
    ('kr', 'Kanuri'),
    ('kk', 'Kazakh'),
    ('km', 'Central Khmer'),
    ('ki', 'Kikuyu; Gikuyu'),
    ('rw', 'Kinyarwanda'),
    ('ky', 'Kirghiz; Kyrgyz'),
    ('kv', 'Komi'),
    ('kg', 'Kongo'),
    ('ko', 'Korean'),
    ('kj', 'Kuanyama; Kwanyama'),
    ('ku', 'Kurdish'),
    ('lo', 'Lao'),
    ('la', 'Latin'),
    ('lv', 'Latvian'),
    ('li', 'Limburgan; Limburger; Limburgish'),
    ('ln', 'Lingala'),
    ('lt', 'Lithuanian'),
    ('lb', 'Luxembourgish; Letzeburgesch'),
    ('lu', 'Luba-Katanga'),
    ('lg', 'Ganda'),
    ('mk', 'Macedonian'),
    ('mh', 'Marshallese'),
    ('ml', 'Malayalam'),
    ('mi', 'Maori'),
    ('mr', 'Marathi'),
    ('ms', 'Malay'),
    ('Mi', 'Micmac'),
    ('mk', 'Macedonian'),
    ('mg', 'Malagasy'),
    ('mt', 'Maltese'),
    ('mn', 'Mongolian'),
    ('mi', 'Maori'),
    ('ms', 'Malay'),
    ('my', 'Burmese'),
    ('na', 'Nauru'),
    ('nv', 'Navajo; Navaho'),
    ('nr', 'Ndebele, South; South Ndebele'),
    ('nd', 'Ndebele, North; North Ndebele'),
    ('ng', 'Ndonga'),
    ('ne', 'Nepali'),
    ('nl', 'Dutch; Flemish'),
    ('nn', 'Norwegian Nynorsk; Nynorsk, Norwegian'),
    ('nb', 'Bokmål, Norwegian; Norwegian Bokmål'),
    ('no', 'Norwegian'),
    ('oc', 'Occitan (post 1500)'),
    ('oj', 'Ojibwa'),
    ('or', 'Oriya'),
    ('om', 'Oromo'),
    ('os', 'Ossetian; Ossetic'),
    ('pa', 'Panjabi; Punjabi'),
    ('fa', 'Persian'),
    ('pi', 'Pali'),
    ('pl', 'Polish'),
    ('pt', 'Portuguese'),
    ('ps', 'Pushto; Pashto'),
    ('qu', 'Quechua'),
    ('rm', 'Romansh'),
    ('ro', 'Romanian; Moldavian; Moldovan'),
    ('ro', 'Romanian; Moldavian; Moldovan'),
    ('rn', 'Rundi'),
    ('ru', 'Russian'),
    ('sg', 'Sango'),
    ('sa', 'Sanskrit'),
    ('si', 'Sinhala; Sinhalese'),
    ('sk', 'Slovak'),
    ('sk', 'Slovak'),
    ('sl', 'Slovenian'),
    ('se', 'Northern Sami'),
    ('sm', 'Samoan'),
    ('sn', 'Shona'),
    ('sd', 'Sindhi'),
    ('so', 'Somali'),
    ('st', 'Sotho, Southern'),
    ('es', 'Spanish; Castilian'),
    ('sq', 'Albanian'),
    ('sc', 'Sardinian'),
    ('sr', 'Serbian'),
    ('ss', 'Swati'),
    ('su', 'Sundanese'),
    ('sw', 'Swahili'),
    ('sv', 'Swedish'),
    ('ty', 'Tahitian'),
    ('ta', 'Tamil'),
    ('tt', 'Tatar'),
    ('te', 'Telugu'),
    ('tg', 'Tajik'),
    ('tl', 'Tagalog'),
    ('th', 'Thai'),
    ('bo', 'Tibetan'),
    ('ti', 'Tigrinya'),
    ('to', 'Tonga (Tonga Islands)'),
    ('tn', 'Tswana'),
    ('ts', 'Tsonga'),
    ('tk', 'Turkmen'),
    ('tr', 'Turkish'),
    ('tw', 'Twi'),
    ('ug', 'Uighur; Uyghur'),
    ('uk', 'Ukrainian'),
    ('ur', 'Urdu'),
    ('uz', 'Uzbek'),
    ('ve', 'Venda'),
    ('vi', 'Vietnamese'),
    ('vo', 'Volapük'),
    ('cy', 'Welsh'),
    ('wa', 'Walloon'),
    ('wo', 'Wolof'),
    ('xh', 'Xhosa'),
    ('yi', 'Yiddish'),
    ('yo', 'Yoruba'),
    ('za', 'Zhuang; Chuang'),
    ('zh', 'Chinese'),
    ('zu', 'Zulu')
]

languagesDict = {
    'Afar': 'aa',
    'Abkhazian': 'ab',
    'Afrikaans': 'af',
    'Akan': 'ak',
    'Albanian': 'sq',
    'Amharic': 'am',
    'Arabic': 'ar',
    'Aragonese': 'an',
    'Armenian': 'hy',
    'Assamese': 'as',
    'Avaric': 'av',
    'Avestan': 'ae',
    'Aymara': 'ay',
    'Azerbaijani': 'az',
    'Bashkir': 'ba',
    'Bambara': 'bm',
    'Basque': 'eu',
    'Belarusian': 'be',
    'Bengali': 'bn',
    'Bihari languages': 'bh',
    'Bislama': 'bi',
    'Tibetan': 'bo',
    'Bosnian': 'bs',
    'Breton': 'br',
    'Bulgarian': 'bg',
    'Burmese': 'my',
    'Catalan; Valencian': 'ca',
    'Czech': 'cs',
    'Chamorro': 'ch',
    'Chechen': 'ce',
    'Chinese': 'zh',
    'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic': 'cu',
    'Chuvash': 'cv',
    'Cornish': 'kw',
    'Corsican': 'co',
    'Cree': 'cr',
    'Welsh': 'cy',
    'Czech': 'cs',
    'Danish': 'da',
    'German': 'de',
    'Divehi; Dhivehi; Maldivian': 'dv',
    'Dutch; Flemish': 'nl',
    'Dzongkha': 'dz',
    'Greek, Modern (1453-)': 'el',
    'English': 'en',
    'Esperanto': 'eo',
    'Estonian': 'et',
    'Basque': 'eu',
    'Ewe': 'ee',
    'Faroese': 'fo',
    'Persian': 'fa',
    'Fijian': 'fj',
    'Finnish': 'fi',
    'French': 'fr',
    'Western Frisian': 'fy',
    'Fulah': 'ff',
    'Georgian': 'Ga',
    'German': 'de',
    'Gaelic; Scottish Gaelic': 'gd',
    'Irish': 'ga',
    'Galician': 'gl',
    'Manx': 'gv',
    'Greek, Modern (1453-)': 'el',
    'Guarani': 'gn',
    'Gujarati': 'gu',
    'Haitian; Haitian Creole': 'ht',
    'Hausa': 'ha',
    'Hebrew': 'he',
    'Herero': 'hz',
    'Hindi': 'hi',
    'Hiri Motu': 'ho',
    'Croatian': 'hr',
    'Hungarian': 'hu',
    'Armenian': 'hy',
    'Igbo': 'ig',
    'Icelandic': 'is',
    'Ido': 'io',
    'Sichuan Yi; Nuosu': 'ii',
    'Inuktitut': 'iu',
    'Interlingue; Occidental': 'ie',
    'Interlingua (International Auxiliary Language Association)': 'ia',
    'Indonesian': 'id',
    'Inupiaq': 'ik',
    'Icelandic': 'is',
    'Italian': 'it',
    'Javanese': 'jv',
    'Japanese': 'ja',
    'Kalaallisut; Greenlandic': 'kl',
    'Kannada': 'kn',
    'Kashmiri': 'ks',
    'Georgian': 'ka',
    'Kanuri': 'kr',
    'Kazakh': 'kk',
    'Central Khmer': 'km',
    'Kikuyu; Gikuyu': 'ki',
    'Kinyarwanda': 'rw',
    'Kirghiz; Kyrgyz': 'ky',
    'Komi': 'kv',
    'Kongo': 'kg',
    'Korean': 'ko',
    'Kuanyama; Kwanyama': 'kj',
    'Kurdish': 'ku',
    'Lao': 'lo',
    'Latin': 'la',
    'Latvian': 'lv',
    'Limburgan; Limburger; Limburgish': 'li',
    'Lingala': 'ln',
    'Lithuanian': 'lt',
    'Luxembourgish; Letzeburgesch': 'lb',
    'Luba-Katanga': 'lu',
    'Ganda': 'lg',
    'Macedonian': 'mk',
    'Marshallese': 'mh',
    'Malayalam': 'ml',
    'Maori': 'mi',
    'Marathi': 'mr',
    'Malay': 'ms',
    'Micmac': 'Mi',
    'Macedonian': 'mk',
    'Malagasy': 'mg',
    'Maltese': 'mt',
    'Mongolian': 'mn',
    'Maori': 'mi',
    'Malay': 'ms',
    'Burmese': 'my',
    'Nauru': 'na',
    'Navajo; Navaho': 'nv',
    'Ndebele, South; South Ndebele': 'nr',
    'Ndebele, North; North Ndebele': 'nd',
    'Ndonga': 'ng',
    'Nepali': 'ne',
    'Dutch; Flemish': 'nl',
    'Norwegian Nynorsk; Nynorsk, Norwegian': 'nn',
    'Bokmål, Norwegian; Norwegian Bokmål': 'nb',
    'Norwegian': 'no',
    'Occitan (post 1500)': 'oc',
    'Ojibwa': 'oj',
    'Oriya': 'or',
    'Oromo': 'om',
    'Ossetian; Ossetic': 'os',
    'Panjabi; Punjabi': 'pa',
    'Persian': 'fa',
    'Pali': 'pi',
    'Polish': 'pl',
    'Portuguese': 'pt',
    'Pushto; Pashto': 'ps',
    'Quechua': 'qu',
    'Romansh': 'rm',
    'Romanian; Moldavian; Moldovan': 'ro',
    'Romanian; Moldavian; Moldovan': 'ro',
    'Rundi': 'rn',
    'Russian': 'ru',
    'Sango': 'sg',
    'Sanskrit': 'sa',
    'Sinhala; Sinhalese': 'si',
    'Slovak': 'sk',
    'Slovak': 'sk',
    'Slovenian': 'sl',
    'Northern Sami': 'se',
    'Samoan': 'sm',
    'Shona': 'sn',
    'Sindhi': 'sd',
    'Somali': 'so',
    'Sotho, Southern': 'st',
    'Spanish; Castilian': 'es',
    'Albanian': 'sq',
    'Sardinian': 'sc',
    'Serbian': 'sr',
    'Swati': 'ss',
    'Sundanese': 'su',
    'Swahili': 'sw',
    'Swedish': 'sv',
    'Tahitian': 'ty',
    'Tamil': 'ta',
    'Tatar': 'tt',
    'Telugu': 'te',
    'Tajik': 'tg',
    'Tagalog': 'tl',
    'Thai': 'th',
    'Tibetan': 'bo',
    'Tigrinya': 'ti',
    'Tonga (Tonga Islands)': 'to',
    'Tswana': 'tn',
    'Tsonga': 'ts',
    'Turkmen': 'tk',
    'Turkish': 'tr',
    'Twi': 'tw',
    'Uighur; Uyghur': 'ug',
    'Ukrainian': 'uk',
    'Urdu': 'ur',
    'Uzbek': 'uz',
    'Venda': 've',
    'Vietnamese': 'vi',
    'Volapük': 'vo',
    'Welsh': 'cy',
    'Walloon': 'wa',
    'Wolof': 'wo',
    'Xhosa': 'xh',
    'Yiddish': 'yi',
    'Yoruba': 'yo',
    'Zhuang; Chuang': 'za',
    'Chinese': 'zh',
    'Zulu': 'zu'
}